name: Build

on:
  push:
  pull_request:
  merge_group:

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Prepare
      run: |
        sudo apt-get update -y
        sudo apt-get install -y pkg-config cmake cmake build-essential clang-tidy ninja-build

    - name: Build with clang-tidy
      run: |
        mkdir clang-tidy
        cd clang-tidy
        cmake -G Ninja -DCMAKE_CXX_CLANG_TIDY="clang-tidy;-warnings-as-errors=*" -DCMAKE_C_CLANG_TIDY="clang-tidy;-warnings-as-errors=*" \
          -DCMAKE_BUILD_TYPE=Debug \
          -DTWBL_DEBUG=ON \
          -Werror=dev ..
        cmake --build . --config Debug

